core/urls.py
from django.contrib.auth.urls import url

from . import views


urlpatterns = [
    #url(r'^thumbnail/$', views.create_thumbnail, name='thumbnail'),
    url(r'^(?P<username>[\w.]+)/$', views.profile, name='profile'),
    url(r'^(?P<username>[\w.]+)/image/$', views.image_profile, name='image_profile'),
    url(r'^(?P<username>[\w.]+)/posts/$', views.list_posts, name='list_posts'), 

]

post/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    
    url(r'^create/$', views.create_or_edit_post, name='create'),
    #url(r'^load/$', views.load_post, name='load_post'),
    
    url(r'^edit/(?P<slug>[-\w]+)/$', views.create_or_edit_post, name='edit'),  
    url(r'^draft/$', views.draft_or_publish_post, name='draft_post'),
    url(r'^publish/$', views.draft_or_publish_post, name='publish_post'),
    
    url(r'^upload/$', views.image_upload, name='image_upload'),
    url(r'^activity/$', views.activity, name='activity'),
    url(r'^(?P<slug>[-\w]+)/$', views.detail, name='detail'),     
    
    url(r'^delete/(?P<slug>[-\w]+)/$', views.delete, name='delete'),

    url(r'^publish/(?P<slug>[-\w]+)/$', views.publish, name='publish'),
    url(r'^comment/(?P<slug>[-\w]+)/$', views.comment, name='comment'),
     
]

viblog/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views

import os
from authentication.views import register
from activity.views import get_dislike, get_like, user_activity


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^draceditor/', include('draceditor.urls')),
    # url(r'^api/', include('activity.urls', namespace='meta')),

    url(r'^login/$', auth_views.login, {'template_name': 'auth/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'login'}, name='logout'),
    url(r'^register/$', register, name='register'),
    #url(r'^', include('post.urls', namespace='post')),

    url(r'^activity/like/$', get_like, name='get_like'),
    url(r'^activity/dislike/$', get_dislike, name='get_dislike'),
    url(r'^activity/user/$', user_activity, name='user_activity'),
    
    url(r'^settings/', include('core.urls', namespace='core')),
    url(r'^check/', include('authentication.urls', namespace='check')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^', include('post.urls', namespace='post')),
    #url(r'^static/(.*)$', 'django.views.static.serve', {'document_root':           
    #os.path.join(os.path.dirname(__file__), 'static')}),

 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

post/models.py
import os

from bs4 import BeautifulSoup
from PIL import Image

from django.conf import settings

from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.core.files import File

from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver

from django.shortcuts import redirect, get_list_or_404

from django.utils.translation import ugettext_lazy as _
from django.utils.text import slugify
from django.utils.module_loading import import_string

from viblog.settings import MARKDOWNX_MARKDOWNIFY_FUNCTION

class Post(models.Model):
    DRAFT = 'D'
    PUBLISHED = 'P'
    STATUS = (
        (DRAFT, 'Draft'),
        (PUBLISHED, 'Published'),
    )

    title = models.CharField(max_length=200)
    slug = models.SlugField()
    content = models.TextField()
    status = models.CharField(max_length=1, choices=STATUS, default=DRAFT)
    author = models.ForeignKey(User)
    date_created = models.DateField(auto_now_add=True, auto_now=False)
    date_updated = models.DateField(auto_now=True, auto_now_add=False )

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = _("Post")
        verbose_name_plural = _("Posts")
        ordering = ('-date_updated','-date_created', '-pk')

    def get_posts(author):
        try:
            list_posts = Post.objects.filter(author=author)
           
            if list_posts is not None:
                return list_posts
            else:
                return False
        except Exception:
            return False
            
    def get_absolute_url(self):
        return reverse('post:detail', kwargs={'slug': self.slug})

    def get_tags(self):
        tags = Tag.objects.filter(post=self, status='A')
        return tags

    def create_tags(self, tags):
        new_tags = tags.strip('').split(', ')
        try:
            tag_list = Tag.objects.filter(post=self)
        except:
            tag_list = None
        if tag_list:
            for old_tag in tag_list: 
                if old_tag not in new_tags:
                    try:
                        old_tag.status = 'R'
                        old_tag.save()
                    except:
                        old_tag.delete()
                        old_tag.save()
                else:
                    pass
        for tag in new_tags:
            Tag.objects.get_or_create(tag=tag.lower(), post=self, status='A')

    def get_comment(self):
        comments = Comment.objects.filter(post=self) 
        return comments

    def create_comments(post, user, comment):
        t, created = Comment.objects.get_or_create(post=post, comment=comment, user=user)

    def get_summary(self):
        if len(self.content) > 150:
            return '{0}...'.format(self.content[:350])
        else:
            return self.content
    
    def get_summary_as_markdown(self):
        markdownify = import_string(MARKDOWNX_MARKDOWNIFY_FUNCTION)
        return markdownify(self.get_summary())

    def get_thumbnail(self):    
        # markdownify = import_string(MARKDOWNX_MARKDOWNIFY_FUNCTION)
        # content = BeautifulSoup(markdownify(self.content))

        # try:
        #     img_link = content.findAll('img')[0].get('src')
        #     print (img_link)
        # except:
        #     img_link = 'http://howtorecordpodcasts.com/wp-content/uploads/2012/10/YouTube-Background-Pop-4.jpg'
        # return img_link
        markdownify = import_string(MARKDOWNX_MARKDOWNIFY_FUNCTION)
        content = BeautifulSoup(markdownify(self.content), "html5lib")
        try:
            img_link = content.findAll('img')[0].get('src')
        except:
            img_link = 'http://howtorecordpodcasts.com/wp-content/uploads/2012/10/YouTube-Background-Pop-4.jpg'
        return img_link


    # def get_likes(self, atype):
    #     values = Activity.objects.filter(activity_type = atype, post=post).count()
    #     return (values)

        
    # def get_likes(self):
    #     t = Activity.calculate_activity(self, atype='L')
    #     return t

    # def get_dislikes(self):
    #     t = Activity.calculate_activity(self, atype='D')
    #     return t

    # def create_like(self, user):
    #     Activity.create_activity(user, self, atype='L')

    # def create_dislike(self, user):
    #     Activity.create_activity(user, self, atype='D')


def pre_post(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(pre_post, sender=Post)

def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by('-id')
    if qs.exists():
        new_slug = "%s%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

class Tag(models.Model):
    ADD = 'A'
    REMOVE = 'R'
    STATUS = (
        (ADD, 'Add'),
        (REMOVE, 'Remove'),
        )
    tag = models.CharField(max_length=100, null=True, blank=True)
    post = models.ForeignKey(Post, null=True)
    status = models.CharField(max_length=1, choices=STATUS, default=REMOVE)

    def __str__(self):
        return self.tag
    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

            
class Comment(models.Model):
    post = models.ForeignKey(Post)
    comment = models.CharField(max_length=1000)
    date_created = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User) 

    def __str__(self):
        return self.comment

post/forms.py
from django import forms

from .models import Post 

from draceditor.fields import DraceditorFormField

class CreatePost(forms.ModelForm):
    content = DraceditorFormField()
    status = forms.CharField(widget=forms.HiddenInput())
    tags = forms.CharField(widget=forms.TextInput(), max_length=250, help_text = "Use ', ' to seperate tags. For example 'tag1, tag2, tag3'")
    
    class Meta: 
        model = Post
        fields = ['status', 'title', 'content','tags']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['status'].initial =  'D'

post/views.py
import os
import json
import uuid

from django.conf import settings
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.http import HttpResponse, JsonResponse, HttpResponseBadRequest
from django.shortcuts import render, get_object_or_404, redirect
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User

from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


from .models import Post
from .forms import CreatePost

from activity.models import Activity

from draceditor.utils import LazyEncoder


def home(request):
    user = request.user
    post_list = Post.objects.all().filter(status='P')#.order_by("-date_created")
    paginator = Paginator(post_list, 12)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        posts = paginator.page(paginator.num_pages)
        return HttpResponseBadRequest('No Page Found')
    
    context = {
        'posts': posts,
        'user': user,
    }
    return render(request, 'post/index.html', context)


# def load_post(request):
#     user = request.user
#     page = int(request.POST.get('next_page_number'))
#     post_list = Post.objects.all().filter(status='P').order_by("-date_created")
#     paginator = Paginator(post_list, 1) # Show 25 contacts per page
#     try:
#         posts = paginator.page(page)
#     except PageNotAnInteger:
#         # If page is not an integer, deliver first page.
#         posts = paginator.page(1)
#     except EmptyPage:
#         # If page is out of range (e.g. 9999), deliver last page of results.
#         posts = paginator.page(paginator.num_pages)
#         return HttpResponseBadRequest('No Page Found')

#     context = {
#         'posts': posts,
#     }
#     return render(request, 'includes/post.html', context)

@login_required
def draft_or_publish_post(request):
    user = request.user
    if user.is_authenticated():
        if request.method == 'POST':
            form = CreatePost(request.POST, request.FILES)
            if form.is_valid():
                title = form.cleaned_data.get('title')
                try:
                    new_post = Post.objects.get(title=title, author=user)
                except:
                    new_post = Post()
                new_post.title = form.cleaned_data.get("title").strip()
                new_post.content = form.cleaned_data.get('content')
                new_post.author = request.user
                status = form.cleaned_data.get('status')
                if status in [Post.PUBLISHED, Post.DRAFT]:
                    new_post.status = status
                else:
                    new_post.status = Post.DRAFT
                new_post.save()
                tags = form.cleaned_data.get('tags')
                if tags:
                    new_post.create_tags(tags)
                return redirect('core:list_posts', username=user.username)
        else:
            return HttpResponseBadRequest('Cannot Process Request')
    else:
        return redirect('login')


def create_or_edit_post(request, slug=None):
    user = request.user
    tags = ''
    if request.method == 'GET':
        if user.is_authenticated:
            if slug:
                post = get_object_or_404(Post, slug=slug, author=user)
                if post:
                    for tag in post.get_tags():
                        tags = '{0} {1},'.format(tags, tag.tag)
                    tags = tags.strip()
                else:
                    return HttpResponseBadRequest('Post Does Not Exists')
                form = CreatePost(instance=post, initial={'tags':tags})
                return render(request, 'post/edit.html', {'form':form})
            else:
                form = CreatePost()
                return render(request, 'post/create.html', {'form':form})
        else:
            return redirect('login')
    else:
        return HttpResponseBadRequest("Invalid Request")
    
def image_upload(request):
    if request.method == 'POST' and request.is_ajax():
        
        if 'markdown-image-upload' in request.FILES:
            image = request.FILES['markdown-image-upload']
            image_types = [
                'image/png', 'image/jpg',
                'image/jpeg', 'image/pjpeg', 'image/gif'
            ]
            if image.content_type not in image_types:
                data = json.dumps({
                    'status': 405,
                    'error': _('Bad image format.')
                }, cls=LazyEncoder)
                return HttpResponse(data, content_type='application/json', status=405)

            img_key = uuid.uuid4().hex[:10]
            img_path = settings.DRACEDITOR_UPLOAD_PATH + str(request.user.username) 

            img_uuid = "{0}-{1}".format(img_key, image.name.replace(' ', '-'))
            tmp_path = os.path.join(img_path, img_uuid)

            def_path = default_storage.save(tmp_path, ContentFile(image.read()))
            img_url = os.path.join(settings.MEDIA_URL, def_path)

            data = json.dumps({
                'status': 200,
                'link': img_url,
                'name': image.name
            })
            return HttpResponse(data, content_type='application/json')
        return HttpResponse(_('Invalid request!'))
    return HttpResponse(_('Invalid request!'))

def detail(request, slug):
    user = request.user
    post = get_object_or_404(Post, slug=slug)
    tags = ''
    for tag in post.get_tags():
        tags = '{0} {1},'.format(tags, tag.tag)
    comments = post.get_comment()
    context = {
        'post': post,
        'tags': tags,
        'comments': comments,
        'user': user,
    }
    return render(request, 'post/list.html', context)


def activity(request):
    if request.method == 'POST':
        user = request.user
        post_slug = request.POST.get('post_slug')
        post = Post.objects.get(slug=post_slug)
        actype = request.POST.get('atype')
        status = True
        like = Activity.objects.filter(activity_type = Activity.LIKE, post=post, user=user)
        dislike = Activity.objects.filter(activity_type = Activity.DISLIKE, post=post, user=user)
        
        if actype in Activity.LIKE:
            atype = Activity.LIKE      
            if not dislike:
                if like:
                    like.delete()
                    status = False
            else:
                 dislike.delete()

        elif actype in Activity.DISLIKE:
            atype = Activity.DISLIKE
            if not like:
                if dislike: 
                    dislike.delete() 
                    status = False   
            else:
                like.delete()
        else:
            return HttpResponseBadRequest()

        if status:
            Activity.create_activity(user, post, atype)
        
        context ={
        }
    
        count = Activity.calculate_activity(post, atype)
        context = {
            'status': True,
            'count': count,
        }
        return JsonResponse(context)

@login_required
def publish(request, slug):
    post = get_object_or_404(Post, slug=slug)
    if post.status is 'D':       
        post.status = 'P'
        post.save()
        return redirect('core:list_posts', username=request.user.username)
    else:
        return HttpResponseBadRequest()


@login_required
def delete(request, slug):
    try:
        post = get_object_or_404(Post, slug=slug)
        post.delete()
    except Exception:
        pass
    return redirect('core:list_posts', username=request.user.username)

@login_required
def comment(request, slug):
    if request.method == 'POST':
        user = request.user
        post = get_object_or_404(Post, slug=slug)
        try:
            user = User.objects.get(username=user.username)
            comment = request.POST.get('comment')
            Post.create_comments(post, user, comment)
            return redirect('post:detail', slug=slug)
        except Exception:
            return redirect('post:detail', slug=slug)
    else:
        return HttpResponseBadRequest()

post/templates/post/create.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load dractags %}

{% block extrahead %}
    <style>
        .container{
            margin-top: 40px;
            margin-bottom: 40px;
        }
    </style>
{% endblock extrahead %}


{% block content %}
<div class="container">
    <form method="POST" action="" id="create-or-edit"  enctype="multipart/form-data"> {% csrf_token %}   
        {{ form.media }}
        {{ form|crispy }}
        <button class="btn btn-info" type="submit" id="draft">Save Draft</button>
        <button class="btn btn-primary" type="submit" id="publish">Publish</button>
    </form>  
</div>
{% endblock content %}

{% block script %}
    <script src="{% static 'js/post.js' %}">
    </script>
{% endblock script %}

post/templates/post/edit.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load dractags %}
{% block content %}
{% block extrahead %}
    <style>
        .container-fluid{
            margin-top: 20px;
            margin-bottom: 20px;
        }
    </style>
{% endblock extrahead %}

<div class="container-fluid">
    <form method="POST" action="" id="create-or-edit"  enctype="multipart/form-data"> {% csrf_token %}   
        {{ form.media }}
        {{ form|crispy }}
        <button class="btn btn-info" type="submit" id="draft">Save Draft</button>
        <button class="btn btn-primary" type="submit" id="publish">Publish</button>
    </form>  
</div>
{% endblock content %}

{% block script %}
    <script src="{% static 'js/post.js' %}">
    </script>
{% endblock script %}

post/templates/post/index.html
{% extends "base.html" %}
{% load static %}
{% block extrahead %}

<style>
.portfolio-item {
    margin-bottom: 30px;
}

.card{
    box-shadow: 0 3px 6px rgba(0,0,0,0.10), 0 2px 2px rgba(0,0,0,0.23);
}


.card-footer{
    background-color:#006699;
    
}

.text-muted{
    color: #eceeef !important;
}

.card-header > a{
    color: #101010;
}

.pagination {
    margin-bottom: 30px;
    
}
.row{
    margin-top: 50px;
}
</style>
{% endblock extrahead %}
{% block content %}

<div class="container">

        <div class="row posts">
            {% include "includes/post.html" with posts=posts user=user %}
        </div>
        <!-- <div class="row">
            <div class="col-md-2 offset-md-5">
                    <button type="submit" id="load" class="btn btn-primary">Load More</button>                    
            </div>
        </div> -->
</div>

    {% if posts.has_previous  or posts.has_next %}
    <nav aria-label="Page navigation example">
        <ul class="pagination justify-content-center">
        {% if posts.has_previous %}
            <!-- <a href="?page={{ posts.previous_page_number }}">previous</a> -->
            <li class="page-item">
                <a class="page-link" href="?page={{ posts.previous_page_number }}" tabindex="-1">Previous</a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link" href="#" tabindex="-1">Previous</a>
            </li>
        {% endif %}

          <li class="page-item"><a class="page-link" href="?page={{ posts.number }}">{{ posts.number }}</a></li>

        {% if posts.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{ posts.next_page_number }}">Next</a>
            </li>
        {% endif %}
        </ul>
    </nav>
    {% endif %}
{% endblock content %}


{% comment %}
{% block script %}
<script type="text/javascript">
    $(document).ready(function(){
        $('#load').click(function(){
            var next_page = $('input[name="next_page"]').val()
            $.ajax({
            url: '{% url "post:load_post" %}',
            type: 'POST',
            data: {'csrfmiddlewaretoken': '{{ csrf_token }}',
            'next_page_number': next_page,
                },
            success: function(data){
                $('.posts button').remove()
                $('input[name="next_page"]').remove()
                $('.posts').append(data)
                }, 
            });
        });
    });
</script>

{% endblock script %}  
{% endcomment %}

post/templates/post/list.html
{% extends "base.html" %}
{% load dractags %}
{% load static %}

{% block extrahead %}
    <style>
            @import url('https://fonts.googleapis.com/css?family=Roboto|PT+Sans');
        .container{
            margin-top: 20px;
            -webkit-box-shadow: 0px 0px 7px 1px rgba(212,205,212,1);
            -moz-box-shadow: 0px 0px 7px 1px rgba(212,205,212,1);
            box-shadow: 0px 0px 3px 1px rgba(212,205,212,1);
            border-radius: 3px 3px 3px 3px;
            -moz-border-radius: 3px 3px 3px 3px;
            -webkit-border-radius: 3px 3px 3px 3px;
            border: 0px solid #fafafa;
            padding: 20px;
            padding-top: 30px;
            padding-left: 40px;
            padding-right: 40px;
            margin-bottom: 30px;
        }
        .content{
            margin-left: 40px;
            margin-right: 40px;
            
        }

        .col-md-12 h3{
            font-size: 30px;
            font-family: 'PT Sans', sans-serif;
        }
        .content p{
            font-family: 'Roboto', sans-serif;
            font-size: 16px;

        }

        .activity button .active{
            background-color: #ddd;
        }
    </style>
    
       
{% endblock extrahead %}

{% block content %}
  <div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3 class="title display-4">{{ post.title }}</h3>
            <small class="lead" style="font-size: 16px;">Author: {{ post.author.userprofile.get_screen_name }} &nbsp | &nbsp {{ post.date_created }}</small>
            <hr>
            <div class="content">
                {{ post.content|safe_markdown }}
            </div>
            <hr>
            <div class="tags">
                {% for tag in post.get_tags %}
                <span class="badge badge-pill badge-primary" style="margin-bottom: 4    px;">{{ tag }}</span>
                {% endfor %}
            </div>
            <br>
            <div class="activity">
                <button type="button" class="btn btn-secondary" id="like">Like <span class="count"></span></button>
                <button type="button" class="btn btn-secondary" id="dislike">Dislike <span class="count"></span></button>
            </div>
            <br><br>
            <div class="comment">
      
                    {% include "includes/comments.html" with comments=comments %}
             <br>

             {% if user.is_authenticated  %}
             <form action="{% url 'post:comment' post.slug %}" method="POST">{% csrf_token %}
                <div class="form-group">
                    <label for="comment">Comment</label>
                    <textarea class="form-control" id="comment" name="comment" rows="3"></textarea><br>
                    <input class="btn btn-outline-info" type="submit" value="submit">
                </div>                 
             </form>
             {% else %}
             <h6>Login to Comment</h6>
             {% endif %}
            </div>
        </div>
    </div>
  </div>
{% endblock content %}

{% block script %}
<script type="text/javascript">
$(document).ready(function(){

    function getlikes(){
        $.ajax({
            url: '{% url "get_like" %}',
            data: {'post_slug': '{{ post.slug }}', 'csrfmiddlewaretoken': '{{ csrf_token }}'},
            type: 'POST',
            dataType: 'json',
            success: function(data){
                if (data.status){
                    if (data.likes == 0){
                        $('.activity #like .count').html('')
                    }else{
                        $('.activity #like .count').html(' | '+ data.likes)
                    }   
                }
            }
        });
        
    }
    function getdislikes(){
        $.ajax({
            url: '{% url "get_dislike" %}',
            data: {'post_slug': '{{ post.slug }}', 'csrfmiddlewaretoken': '{{ csrf_token }}'},
            type: 'POST',
            dataType: 'json',
            success: function(data){
                if (data.status){
                    if (data.dislikes == 0){
                        $('.activity #dislike .count').html('')
                }else{
                        $('.activity #dislike .count').html(' | '+ data.dislikes)
                    }
                    
                }
            }
        });
    }
        getlikes()
        getdislikes()
        getUserActivity()

        $('#like').click(function(){
            $.ajax({
                url: '/activity/',
                type: 'POST',
                data: {
                    'post_slug': '{{ post.slug }}',
                     csrfmiddlewaretoken: '{{ csrf_token }}',
                     'atype': 'L'
                },
                dataType: 'json',
                success: function(data){
                    if (data.status == true){
                        $('.activity button').removeClass('active')
                        $('.activity #like').addClass('active')
                        if (data.count == 0){
                            $('.activity #like .count').html('')
                        }else{
                            $('.activity #like .count').html(' | '+ data.count)
                        }
                        getdislikes()
                        getUserActivity()
                        }
                }
            });
        });
        $('#dislike').click(function(){
            $.ajax({
                url: '{% url "post:activity" %}',
                type: 'POST',
                data: {
                    'post_slug': '{{ post.slug }}',
                     csrfmiddlewaretoken: '{{ csrf_token }}',
                     'atype': 'D'
                },
                dataType: 'json',
                success: function(data){
                    if (data.status == true){
                        $('.activity button').removeClass('active')
                        $('.activity #dislike').addClass('active')
                        if (data.count == 0){
                            $('.activity #dislike .count').html('')
                        }else{
                            $('.activity #dislike .count').html(' | '+ data.count)
                        }
                        getlikes()
                        getUserActivity()
                        }
                }
            });
        });

        function getUserActivity(){
            $.ajax({
              url: '{% url "user_activity" %}',
              type: 'POST',
              data: {'csrfmiddlewaretoken': '{{ csrf_token }}', 
              'post_slug': '{{ post.slug }}'
            },
              dataType: 'json',
              success: function(data){
                  if (data.status){
                      if(data.atype == 'D'){
                        $('.activity button').removeClass('active')
                        $('.activity #dislike').addClass('active')
                      }else if (data.atype == 'L'){
                        $('.activity button').removeClass('active')
                        $('.activity #like').addClass('active')
                      }
                  }else{
                    $('.activity button').removeClass('active')
                  }
              }
                
            })
        }
    }) ;
</script>

{% endblock script %}