core/urls.py
from django.contrib.auth.urls import url

from . import views


urlpatterns = [
    #url(r'^thumbnail/$', views.create_thumbnail, name='thumbnail'),
    url(r'^(?P<username>[\w.]+)/$', views.profile, name='profile'),
    url(r'^(?P<username>[\w.]+)/image/$', views.image_profile, name='image_profile'),
    url(r'^(?P<username>[\w.]+)/posts/$', views.list_posts, name='list_posts'), 

]

post/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    
    url(r'^create/$', views.create_or_edit_post, name='create'),
    #url(r'^load/$', views.load_post, name='load_post'),
    
    url(r'^edit/(?P<slug>[-\w]+)/$', views.create_or_edit_post, name='edit'),  
    url(r'^draft/$', views.draft_or_publish_post, name='draft_post'),
    url(r'^publish/$', views.draft_or_publish_post, name='publish_post'),
    
    url(r'^upload/$', views.image_upload, name='image_upload'),
    url(r'^activity/$', views.activity, name='activity'),
    url(r'^(?P<slug>[-\w]+)/$', views.detail, name='detail'),     
    
    url(r'^delete/(?P<slug>[-\w]+)/$', views.delete, name='delete'),

    url(r'^publish/(?P<slug>[-\w]+)/$', views.publish, name='publish'),
    url(r'^comment/(?P<slug>[-\w]+)/$', views.comment, name='comment'),
     
]

search/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.search_query, name="search_query"),
]

viblog/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views

import os
from authentication.views import register
from activity.views import get_dislike, get_like, user_activity


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^draceditor/', include('draceditor.urls')),
    # url(r'^api/', include('activity.urls', namespace='meta')),

    url(r'^login/$', auth_views.login, {'template_name': 'auth/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'login'}, name='logout'),
    url(r'^register/$', register, name='register'),
    #url(r'^', include('post.urls', namespace='post')),

    url(r'^activity/like/$', get_like, name='get_like'),
    url(r'^activity/dislike/$', get_dislike, name='get_dislike'),
    url(r'^activity/user/$', user_activity, name='user_activity'),
    
    url(r'^settings/', include('core.urls', namespace='core')),
    url(r'^check/', include('authentication.urls', namespace='check')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^', include('post.urls', namespace='post')),
    #url(r'^static/(.*)$', 'django.views.static.serve', {'document_root':           
    #os.path.join(os.path.dirname(__file__), 'static')}),

 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/includes/header.html
<style>

</style>

<nav class="navbar navbar-toggleable-md navbar-light bg-faded" style="">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href="{% url 'post:home' %}">ViBlog</a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'post:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
    </ul>
    <div class="col-md-4" style="margin-right: 460px;">
        <div class="input-group">
          <form role="search" class="input-group" action="{% url 'search:search_query' %}" method="GET">
              <input type="text" name="q" class="form-control" placeholder="Search for..." value="{{ request.GET.q }}">
              <span class="input-group-btn">
                <button class="btn btn-secondary" type="submit">Go!</button>
              </span>
          </form>
   
        </div>
      </div>
    <ul class="navbar-nav">
      {% if request.user.is_authenticated %}
      <li class="nav-item">
          <a class="nav-link" href="{% url 'post:create' %}">New Article</a>
      </li>
      <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Settings
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{% url 'core:profile' user.username %}">Profile</a>
              <a class="dropdown-item" href="{% url 'core:list_posts' user.username %}">Editor</a>
              <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
          </div>
      </li>

        {% else %}
      <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}">Login</a>
      </li>
      <li class="nav-item">
          <a class="nav-link" href="{% url 'register' %}">Register</a>
      </li>
        {% endif %}
    </ul>
  </div>
</nav>