core/urls.py
from django.contrib.auth.urls import url

from . import views


urlpatterns = [
    #url(r'^thumbnail/$', views.create_thumbnail, name='thumbnail'),
    url(r'^(?P<username>[\w.]+)/$', views.profile, name='profile'),
    url(r'^(?P<username>[\w.]+)/image/$', views.image_profile, name='image_profile'),
    url(r'^(?P<username>[\w.]+)/posts/$', views.list_posts, name='list_posts'), 

]

post/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    
    url(r'^create/$', views.create_or_edit_post, name='create'),
    #url(r'^load/$', views.load_post, name='load_post'),
    
    url(r'^edit/(?P<slug>[-\w]+)/$', views.create_or_edit_post, name='edit'),  
    url(r'^draft/$', views.draft_or_publish_post, name='draft_post'),
    url(r'^publish/$', views.draft_or_publish_post, name='publish_post'),
    
    url(r'^upload/$', views.image_upload, name='image_upload'),
    url(r'^activity/$', views.activity, name='activity'),
    url(r'^(?P<slug>[-\w]+)/$', views.detail, name='detail'),     
    
    url(r'^delete/(?P<slug>[-\w]+)/$', views.delete, name='delete'),

    url(r'^publish/(?P<slug>[-\w]+)/$', views.publish, name='publish'),
    url(r'^comment/(?P<slug>[-\w]+)/$', views.comment, name='comment'),
     
]

viblog/urls.py
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.auth import views as auth_views

import os
from authentication.views import register
from activity.views import get_dislike, get_like, user_activity


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^draceditor/', include('draceditor.urls')),
    # url(r'^api/', include('activity.urls', namespace='meta')),

    url(r'^login/$', auth_views.login, {'template_name': 'auth/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout, {'next_page': 'login'}, name='logout'),
    url(r'^register/$', register, name='register'),
    #url(r'^', include('post.urls', namespace='post')),

    url(r'^activity/like/$', get_like, name='get_like'),
    url(r'^activity/dislike/$', get_dislike, name='get_dislike'),
    url(r'^activity/user/$', user_activity, name='user_activity'),
    
    url(r'^settings/', include('core.urls', namespace='core')),
    url(r'^check/', include('authentication.urls', namespace='check')),
    url(r'^search/', include('search.urls', namespace='search')),
    url(r'^', include('post.urls', namespace='post')),
    #url(r'^static/(.*)$', 'django.views.static.serve', {'document_root':           
    #os.path.join(os.path.dirname(__file__), 'static')}),

 
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

core/forms.py
from django import forms
from django.contrib.auth.models import User

from authentication.models import UserProfile

class UserProfileForm1(forms.ModelForm):

    # dob = forms.DateField(input_formats=['%d-%m-%Y'])
    # state = forms.CharField()
    # country = forms.CharField()
    # mobile = forms.IntegerField()
    # alternate_email = forms.EmailField()
    # intro_slogan = forms.CharField()

    class Meta:
        model = User
        fields = ['first_name', 'last_name' ]

class UserProfileForm2(forms.ModelForm):
    dob = forms.CharField(widget=forms.TextInput(attrs={'type':'date'}))
    class Meta:
        model = UserProfile
        fields = ['dob','state', 'country', 'mobile', 'alternate_email']

    def __init__(self, *args, **kwargs):
        super(UserProfileForm2, self).__init__(*args, **kwargs)
        self.fields['dob'].widget.format = '%d-%m-%Y'
        self.fields['dob'].input_formats = ['%d-%m-%Y']

class UserImageForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ['profile_image']

core/views.py
from PIL import Image
from bs4 import BeautifulSoup
import os
import django

from django.core.files import File

from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.conf import settings

from django.forms import formset_factory

from django.http import HttpResponse, JsonResponse, HttpResponseBadRequest

from django.template.loader import render_to_string

from django.shortcuts import render, get_object_or_404, redirect, get_list_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


from .forms import UserProfileForm1, UserProfileForm2, UserImageForm
from post.models import Post

from viblog.settings import MARKDOWNX_MARKDOWNIFY_FUNCTION
from django.utils.module_loading import import_string


EXTENSION = ['jpg', 'png', 'jpeg']

@login_required
def profile(request, username):
    user = request.user
    if request.method == 'GET':
        context = {
            'form': UserProfileForm1(instance=user),
            'userform': UserProfileForm2(instance=user.userprofile),
            'user': user,
            'image': user.userprofile.get_profile_picture_url,
        }
        return render(request, 'core/profile.html', context)
    else:
        userprofileform1 = UserProfileForm1(request.POST)
        userprofileform2 = UserProfileForm2(request.POST)
        if userprofileform1.is_valid() and userprofileform2.is_valid():
            try:
                if User.objects.get(username=user.username) is not None:
                    user.first_name = userprofileform1.cleaned_data.get('first_name')
                    user.last_name = userprofileform1.cleaned_data.get('last_name')
                    user.userprofile.dob = userprofileform2.cleaned_data.get('dob')
                    user.userprofile.state = userprofileform2.cleaned_data.get('state')
                    user.userprofile.country = userprofileform2.cleaned_data.get('country')
                    user.userprofile.mobile = userprofileform2.cleaned_data.get('mobile')
                    user.userprofile.alternate_email = userprofileform2.cleaned_data.get('alternate_email')
                    user.save()
                    return redirect('core:profile', username = user.username)
                else:
                    return HttpResponseBadRequest()
            except Exception:
                return HttpResponseBadRequest()
        else:
            return HttpResponseBadRequest()


@login_required
def image_profile(request, username):
    user = request.user
    if request.method == "POST":
        image = request.FILES.get('file')
        file_path = settings.BASE_DIR + settings.MEDIA_URL + 'profile-images/' + user.username
        user.userprofile.profile_image = image
        user.save()
        file_name = user.userprofile.profile_image.url
        file_name = file_name.split('/')[-1]
        im = Image.open(file_path + '/' + file_name)
        width, height = (im.size)
        if width > height:
            x = 0 + int((width-height))/2
            y = 0
            w = width - int((width-height))/2
            h = height
        elif height > width:
            x = 0
            y = 0 + (height - width)/2
            w = width
            h = height - (height - width)/2
        else:
            pass
        try:
            im = im.crop((x, y, w, h))
        except: 
            pass
        im.save(file_path + '/' + file_name)
        return HttpResponse(True)
    else:
        image_url = user.userprofile.get_profile_picture_url
        context = {
            'status': True,
            'url': image_url
        }
        return JsonResponse(context)

@login_required
def list_posts(request, username):
    if request.method == 'GET':
        user = request.user
        post_list = Post.get_posts(user)
        paginator = Paginator(post_list, 10) # Show 25 contacts per page
        page = request.GET.get('page')
        try:
            posts = paginator.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            posts = paginator.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            posts = paginator.page(paginator.num_pages)
            return HttpResponseBadRequest('No Page Found')
        
        context = {
            'posts': posts,
        }
        return render(request, 'core/list_post.html', context)


# def create_thumbnail(request):
    # slug = 'samsung-galaxy-note8-hands-on-review'
    # post = get_object_or_404(Post, slug=slug)
    # if post:
    #     markdownify = import_string(MARKDOWNX_MARKDOWNIFY_FUNCTION)
    #     content = BeautifulSoup(markdownify(post.content), "html5lib")
    #     try:
    #         img_link = content.findAll('img')[0].get('src')
    #         file_path = settings.BASE_DIR + img_link
    #         file_full_name = img_link.split('/')[-1]
    #         file_name, extension = file_path.split('.')
    #         file_name = file_name.split('/')[-1]
    #         try:
    #             if extension in EXTENSION:
    #                 username = post.author.username
    #                 new_file_path = settings.BASE_DIR + settings.STATIC_URL + 'media' + '/' + settings.DRACEDITOR_UPLOAD_PATH + post.author.username + '/' + post.slug + '/'
    #                 new_file_name = new_file_path + file_name + '-thumbnail'
    #                 if not os.path.exists(new_file_path):
    #                     print ('HERE')
    #                     os.makedirs(new_file_path)
    #                 im = Image.open(file_path)
    #                 width, height = (im.size)
    #                 if width > height:
    #                     x = 0 + int((width-height))/2
    #                     y = 0
    #                     w = width - int((width-height))/2
    #                     h = height
    #                 elif height > width:
    #                     x = 0
    #                     y = 0 + (height - width)/2
    #                     w = width
    #                     h = height - (height - width)/2
    #                 else:
    #                     pass
    #                 im = im.crop((x, y, w, h))
                  
    #                 width, height = (im.size)
    #                 im.save(new_file_name + '.' + extension)
                    
    #         except:
    #             raise Exception('Please Upload Correcct Image Format')
    #     except:
    #         img_link = 'http://howtorecordpodcasts.com/wp-content/uploads/2012/10/YouTube-Background-Pop-4.jpg'
        
    #     context = {
    #         'post': post, 
    #         'username': post.author.username,
    #         'file': new_file_name + '.' + extension,
    #     }
        
    #     return render(request, 'core/example.html', context)

core/templates/core/list_post.html
{% extends "base.html" %}

{% block content %}

    <div class="container" style="margin-bottom: 30px;">
        <div class="row col-md-12" style="margin-top:40px;">
                {% if posts %}
        <table class="table table-striped">
        <thead>
            <tr>
                <th></th>
                <th>Title</th>
                <th></th>
                <th></th>
                
                <th></th>
            </tr>
        </thead>
            
                {% for post in posts %}
                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td colspan="3">{{ post.title }}</td>
                   
                        <td class="text-right">
                            <a class='btn btn-info btn-xs' href="{% url 'post:edit' post.slug %}"><span class="glyphicon glyphicon-edit"></span> Edit</a> 
                            <a href="{% url 'post:detail' post.slug %}" class="btn btn-info btn-xs"><span class="glyphicon glyphicon-view"></span> View</a>
                            <a href="{% url 'post:delete' post.slug %}" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span> Delete</a>
                            {% if post.status == "D" %}
                            <a href="{% url 'post:publish' post.slug %}" class="btn btn-primary btn-xs"><span class="glyphicon glyphicon-remove"></span> Publish</a>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                {% else %}
                <h3 style="margin-top: 200px; margin-left: 400px;">
                        No Post Found <br>
                        <a href="{% url 'post:create' %}"><small class="text-muted">Create New Post</small></a>
                      </h3>
            {% endif %}
        </table>
        </div>
    </div>
    
    {% if posts.has_previous or posts.has_next %}
    <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center">
    
    
            {% if posts.has_previous %}
                {% comment %} <a href="?page={{ posts.previous_page_number }}">previous</a> {% endcomment %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ posts.previous_page_number }}" tabindex="-1">Previous</a>
                </li>
            {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#" tabindex="-1">Previous</a>
                </li>
            {% endif %}
    
              <li class="page-item"><a class="page-link" href="?page={{ posts.number }}">{{ posts.number }}</a></li>
    
            {% if posts.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ posts.next_page_number }}">Next</a>
                </li>
            {% endif %}
            </ul>
        </nav>
        {% endif %}
{% endblock content %}

core/templates/core/profile.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block extrahead %}
  <style media="screen">
    .account-settings{
      margin-top: 20px;
    }
  </style>
    <script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
  <script src="{% static 'js/jquery-file-upload/vendor/jquery.ui.widget.js' %}"></script>
  <script src="{% static 'js/jquery-file-upload/jquery.iframe-transport.js' %}"></script>
  <script src="{% static 'js/jquery-file-upload/jquery.fileupload.js' %}"></script>
{% comment %}<script src="https://code.jquery.com/jquery-3.2.1.js" integrity="sha256-DZAnKJ/6XZ9si04Hgrsxu/8s717jcIzLy3oi35EouyE=" crossorigin="anonymous"></script>{% endcomment %}
  {# PHOTOS PAGE SCRIPTS #}
  <script src="{% static 'js/basic-upload.js' %}"></script>

{% endblock %}

{% block content %}

  <div class="container account-settings">
    <h4>Account Settings</h4>
    <hr>
    <div class="row">
      <div class="col-md-3 profile">
        {% include "core/profile_image.html" with user=user %}
      <!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
  Change
</button>
</div>
        
      <div class="col-md-9">
       <ul class="nav nav-tabs justify-content-end" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" href="#form1">Personal</a>
          </li>
        </ul>
        <div class="tab-content">

          <div role="tabpanel" class="col-md-10 offset-md-1 tab-pane active" id="form1"><br>
            {% comment %} <form action="" method="POST">{% csrf_token %}
              <div class="form-group row">
                <label for="{{ form.first_name.id_for_label }}" class="col-3 col-form-label">{{ form.first_name.label }}</label>
                <div class="col-9">
                  <input class="form-control" type="text" value="{{ form.first_name.value }}" id="example-text-input">
                </div>
              </div>
              <div class="form-group row">
                <label for="{{ form.last_name.id_for_label }}" class="col-3 col-form-label">{{ form.last_name.label }}</label>
                <div class="col-9">
                  <input class="form-control" type="text" value="{{ form.last_name.value }}" id="example-text-input">
                </div>
              </div>
              <div class="form-group row">
                <label for="{{ form.dob.id_for_label }}" class="col-3 col-form-label">{{ form.dob.label }}</label>
                <div class="col-9">
                  <input class="form-control" type="date" value="{{ form.dob.value }}" id="{{ form.dob.id_for_label }}">
                </div>
              </div>
              <div class="form-group row">
                <label for="{{ form.country.id_for_label }}" class="col-3 col-form-label">{{ form.country.label }}</label>
                <div class="col-9">
                  <input class="form-control" type="text" value="{% if form.country.value %}{{ form.country.value }}{% endif %}" id="{{ form.country.id_for_label }}">
                </div>
              </div>            
              <div class="form-group row">
                <label for="{{ form.state.id_for_label }}" class="col-3 col-form-label">{{ form.state.label }}</label>
                <div class="col-9">
                  <input class="form-control" type="text" value="{% if form.state.value %}{{ form.state.value }}}{% endif %}" id="{{ form.state.id_for_label }}">
                </div>
              </div>
              <div class="form-group row">
                <label for="{{ profile.mobile.id_for_label }}" class="col-3 col-form-label">{{form.mobile.label}}</label>
                <div class="col-9">
                  <input class="form-control" type="tel" value="{% if form.mobile.value %}{{ form.mobile.value }}{% endif %}" id="{{ profile.mobile.id_for_label }}">
                </div>
              </div>
              <div class="form-group row">
                <label for="{{ form.alternate_email.id_for_label }}" class="col-3 col-form-label">{{ form.alternate_email.label }}</label>
                <div class="col-9">
                  <input class="form-control" type="email" value="{% if form.alternate_email.value %}{{ form.alternate_email.value }}{% endif %}" id="{{ form.alternate_email.id_for_label }}">
                </div>
              </div>
              <div class="form-group row">
                <label for="{{ form.intro_slogan.id_for_label }}" class="col-3 col-form-label">{{ form.intro_slogan.label }}</label>
                <div class="col-9">
                  <input class="form-control" type="text" value="{% if form.intro_slogan.value %}{{ form.intro_slogan.value }}}{% endif %}" id="{{ form.state.id_for_label }}">
                </div>
              </div>
              <input  class="btn btn-outline-primary" type="submit" name="submit" value="Save">
            </form> {% endcomment %}

            <form action="" method="POST">{% csrf_token %}
              {{ form|crispy}}
              {{ userform|crispy }}
              <input class="btn btn-outline-primary" type="submit" name="submit" value="Save">
            </form>
      
          </div>
          <div role="tabpanel" class="tab-pane" id="form2">bbb</div>
          <div role="tabpanel" class="tab-pane" id="form3">ccc</div>
        </div> 

      </div>
    </div>
  </div>
<hr>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Profile Image</h5>
        
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <small class="text-muted" style="margin: 12px;">*Please upload square pixel image for better viewing</small>
      <div class="modal-body">
        Upload
        <div class="image-upload">
          {% include "core/upload.html" with user=user %}
        </div>  
      </div>
    </div>
  </div>
</div>


{% endblock content %}

core/templates/core/profile_image.html
<div class="profile-image">
<h5>Profile Picture</h5><br>

    <img width="200px" height="200px" src="{{ user.userprofile.get_profile_picture_url }}" name='profile' alt="" class="img-fluid">
    <hr>          
</div>

core/templates/core/upload.html
{% load static %}


  {# JQUERY FILE UPLOAD SCRIPTS #}
  <!-- Latest compiled and minified CSS -->

  <div style="margin-bottom: 20px;">
  <div style="margin-bottom: 20px;"><br>
    <button type="button" class="btn btn-primary js-upload-photos">
      <span class="glyphicon glyphicon-cloud-upload"></span> Upload Image
    </button>
    <input id="fileupload" type="file" name="file"
           style="display: none;"
           data-url="{% url 'core:image_profile' user %}"
           data-form-data='{"csrfmiddlewaretoken": "{{ csrf_token }}"}'>
  </div>

  <div class="modal fade" id="modal-progress" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Uploading...</h4>
        </div>
        <div class="modal-body">
          <div class="progress">
            <div class="progress-bar" role="progressbar" style="width: 0%;">0%</div>
          </div>
        </div>
      </div>
    </div>
  </div>